# Generated by Django 3.2.3 on 2021-05-27 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210527_2157'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='TUser',
        ),
    ]
