# Generated by Django 3.2.3 on 2021-05-28 11:32

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_tasks_task_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_pic',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=tasks.models.upload_path),
        ),
    ]
