# Generated by Django 3.2.3 on 2021-05-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dis',
            name='ParentID',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
